### ISSUE TITLE
Videos does not work on Android when used with google_mobile_ads on the same page

### ISSUE THREAD

**Issue by mnorhamizan** [SmallDreams/youtube_plyr_iframe#33]
**Describe the bug**
Whenever youtube_plyr_iframe is used in together with google_mobile_ads in the same page, the video would either not play properly or it would only plays the audio.

**To Reproduce:**
Use youtube_plyr_iframe in the same page with google_mobile_ads.

**Expected behavior:**
The player should be able to work with other plugins

**Flutter Doctor:**
<details>
  <summary>Click to expand!</summary>
  
```
[✓] Flutter (Channel unknown, 1.22.6, on Mac OS X 10.15.7 19H1217 darwin-x64, locale en-MY)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 12.4)
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.57.0)
[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
```
</details>

**Comment by jonafeucht** [comment]
As stated by sarbagyastha:
`But the package will only be optimzed to use single player per page. It won't support list of player as it's very complex to handle fullscreen switch, with multiple players that too with existing limitations of platform views. The new package should be used for the purpose.`

Meaning, since both make use of PlatformView it with give back the error you're encountering.
